#!/bin/sh
# Report ACPI battery information in compact form.

acpi -b | sed -rn '/^Battery 0:/ {
 s/^Battery.*: //
 s/,//g
 s/Unknown/=/
 s/Discharging/-/
 s/Charging/+/
 s/remaining//
 s/until charged//
 # Skip seconds.
 s/:[0-9][0-9] //
 # Skip leading zeros and hours if empty.
 s/ 0+/ /
 s/ :/ /
 s/ 0+/ /
 p
 }'

